Added basic handling for application logs
laravel/octane pull request #325
Opened 2021-06-14 11:41 UTC by Radiergummi

This PR adds support for application logs written to stderr, as described in #320. As it stands, logging to stderr isn't possible in Octane, defeating best practices for Docker deployments.

For reference, here's my last post in that issue:
> For context on the issue itself, as Roadrunner uses stdout as its response transmission channel, it files all stderr output as application logs, with a level of `INFO`. This does not match any condition in the `getIncrementalOutput` line handler callback, and is discarded. So we can get application logs into the output by simply adding the following: [...]
>
> This has a few downsides, however:
> - **It prints noise messages:** Unfortunately, RR sends additional, non-app logs under the same channel ("INFO  scan command"). There's not really a good way to prevent this other than blacklisting them.
> - **It hard-codes INFO as the log level:** As we don't know which formatter the user has configured for the stderr logger, we can't simply parse the application-generated log line to extract the actual log level, and thus are forced to use INFO.
> - **It relies on an implementation detail:** This is of lesser concern, but (ab)using the `logger` field of the Roadrunner output for something it probably isn't intended for seems brittle to me.
>
> The first two points could be solved by adding special handling to Laravel itself: If it is running within Octane, log lines could be prefixed by some unique identifier, independently of the configured line formatter. That would allow checking for a substring match on the info lines received and only printing those.  
> Another option might be for Roadrunner itself to label application output differently, or adding a meta field to the log JSON.  
>
> Alternatively, we could simply add the three lines above and call it a day.

Anyone has ideas on how to go forward?

2021-06-14 11:45 UTC, driesvints commented
@Radiergummi just want to remind you that PR's aren't reviewed until they're out of draft: https://laravel.com/docs/8.x/contributions#bug-reports

2021-06-14 14:23 UTC, nunomaduro commented
@Radiergummi Can you give me an example of a "logging" message that you think people would want to see and is currently missing on the octane output?

2021-06-14 15:17 UTC, Namoshek commented
Noteworthy @nunomaduro, the `stderr` logger works with Swoole already, only RR misses special handling.

2021-06-14 17:06 UTC, Namoshek commented
I'm having some trouble getting the `stderr` output to work. Would be nice to have the `stderr` logger actually log to `stderr`. I'm not sure if it is a WSL 2 issue though. Normally, within a command, `$this->getOutput()->getErrorStyle()` would return the `OutputStyle` for `stderr`. But for some reason it does not and the `stdout` one is returned instead (I see where the decision is made, but not why there is no `stderr` one assigned).

Anyway, the suggested solution does unfortunately not seem to work with the current existing configuration, because the `logs.level` parameter of RR is `debug` for `local` environments and `warning` for other environments (`production`, etc.). This will make `info` messages from RR vanish in production, removing all log output. Easy to test with `APP_ENV=production`.
    https://github.com/laravel/octane/blob/9ec7fa0052a56e46688165385ea02dfba0d43de7/src/Commands/StartRoadRunnerCommand.php#L87-L88

---

If we somehow get this to work, we should log the output without formatting for better readability and processability using `$this->getOutput()->writeln(trim($debug['msg']))` though. In my opinion it would also be nice if it was possible to change the formatting and/or disable the logging of requests (`200  GET  / .... 1ms`) as well - as part of another PR. Maybe this could even be done in the base `Command` class for all types of output.

2021-06-14 17:07 UTC, Namoshek requested changes
Just leaving a review to avoid accidental merging.

2021-06-14 17:07 UTC, Namoshek commented on src/Commands/StartRoadRunnerCommand.php
> +                if ($debug['level'] === 'info' && $debug['logger'] === 'server') {
`$debug['level'] === 'info'` messages are not present in `APP_ENV=production`.

2021-06-14 17:39 UTC, Namoshek commented
The issue with `$debug['level'] === 'info'` seems fixable by adding `'-o', 'logs.channels.server.mode=production',` as RR parameter, which will override the log mode for the server channel only.

2021-06-14 18:21 UTC, Namoshek commented
Yes, using `--server=swoole` outputs the log messages as error messages:
```
ERROR  [2021-06-14 18:19:12] production.ERROR: test
```

The logs seem to be printed on `stdout` though, since the following command shows no output at all:
```sh
 php artisan octane:start --server=swoole >/dev/null
```

2021-06-14 18:25 UTC, nunomaduro commented
@Namoshek Alright - that is expected behavior? Or something seems odd there?

2021-06-14 18:27 UTC, Namoshek commented
Yeah, after thinking about it for another 2 minutes, I would say this cannot be intentional. Why should logs be printed as errors? Is it possible we are hitting the following code (by accident)?

https://github.com/laravel/octane/blob/9ec7fa0052a56e46688165385ea02dfba0d43de7/src/Commands/StartSwooleCommand.php#L179-L182

2021-06-14 19:11 UTC, nunomaduro commented
Currently investigating and working on this.

2021-06-15 13:13 UTC, nunomaduro commented
@Radiergummi @Namoshek Can you try this pull request https://github.com/laravel/octane/pull/326 on both drivers `swoole` and `roadrunner`, and let me know how it goes?

2021-06-15 13:13 UTC, closed without merging